/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    verreries: Verrery;
    personnalites: Personnalite;
    verriers: Verrier;
    'types-de-production': TypesDeProduction;
    engagements: Engagement;
    lieux: Lieux;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    verreries: VerreriesSelect<false> | VerreriesSelect<true>;
    personnalites: PersonnalitesSelect<false> | PersonnalitesSelect<true>;
    verriers: VerriersSelect<false> | VerriersSelect<true>;
    'types-de-production': TypesDeProductionSelect<false> | TypesDeProductionSelect<true>;
    engagements: EngagementsSelect<false> | EngagementsSelect<true>;
    lieux: LieuxSelect<false> | LieuxSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'fr' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verreries".
 */
export interface Verrery {
  id: number;
  nomPrincipal: string;
  slug: string;
  nomsAlternatifs?:
    | {
        typeDeNom?: ('raisonSociale' | 'nomUsage' | 'nomMaitreVerrier' | 'nomLieuDit' | 'autre') | null;
        nom: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Personnalités ayant fondé cet établissement.
   */
  fondateurs?: (number | Personnalite)[] | null;
  dateDeCreation?: {
    datePreciseCreation?: string | null;
    descriptionDateCreation?: string | null;
  };
  dateDeFermeture?: {
    datePreciseFermeture?: string | null;
    descriptionDateFermeture?: string | null;
  };
  statutActuel?:
    | (
        | 'enActivite'
        | 'fermeeDefinitivement'
        | 'fermeeTemporairement'
        | 'enRuines'
        | 'disparueSansVestiges'
        | 'convertie'
      )
    | null;
  notesStatutVestiges?: string | null;
  /**
   * Sélectionnez ou créez le lieu où cette verrerie est (ou était) implantée.
   */
  lieuPrincipal?: (number | null) | Lieux;
  /**
   * Liez ici les personnalités (directeurs, etc.) et les verriers (ouvriers, artisans) avec leurs fonctions et périodes spécifiques à cette verrerie.
   */
  engagements?: (number | Engagement)[] | null;
  typesDeProduction?: (number | TypesDeProduction)[] | null;
  imagesEtMedias?: (number | Media)[] | null;
  sourcesBibliographiques?:
    | {
        typeSource?: ('livre' | 'article' | 'siteWeb' | 'archive' | 'entretien' | 'autre') | null;
        titre?: string | null;
        auteur?: string | null;
        url?: string | null;
        detailsPublication?: string | null;
        citationOuExtrait?: string | null;
        notesSource?: string | null;
        id?: string | null;
      }[]
    | null;
  histoire?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  techniquesInnovations?: string | null;
  aspectsSociaux?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnalites".
 */
export interface Personnalite {
  id: number;
  nom: string;
  prenom?: string | null;
  /**
   * Généré automatiquement si laissé vide, ou peut être saisi manuellement.
   */
  nomComplet?: string | null;
  slug?: string | null;
  rolePrincipal: 'fondateur' | 'directeur' | 'maitre_verrerie' | 'proprietaire' | 'associe' | 'ingenieur' | 'autre';
  /**
   * Ex: "vers 1750", "le 12/03/1810"
   */
  dateDeNaissance?: string | null;
  /**
   * Sélectionnez le lieu de naissance si connu.
   */
  lieuDeNaissance?: (number | null) | Lieux;
  /**
   * Ex: "vers 1820", "le 01/10/1880"
   */
  dateDeDeces?: string | null;
  /**
   * Sélectionnez le lieu de décès si connu.
   */
  lieuDeDeces?: (number | null) | Lieux;
  biographie?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lieux".
 */
export interface Lieux {
  id: number;
  nomDuLieu?: string | null;
  adresse?: string | null;
  /**
   * Ex: Rive-de-Gier, Givors, Saint-Étienne
   */
  villeOuCommune: string;
  codePostal?: string | null;
  /**
   * Ex: Loire, Rhône
   */
  departement?: string | null;
  /**
   * Ex: Auvergne-Rhône-Alpes
   */
  region?: string | null;
  pays: string;
  /**
   * Cliquez sur la carte pour définir le point, ou entrez manuellement longitude puis latitude.
   *
   * @minItems 2
   * @maxItems 2
   */
  coordonnees: [number, number];
  notesHistoriquesSurLeLieu?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  nomCompletAffichage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Définit le rôle ou le métier d'une personne dans une verrerie sur une période donnée.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagements".
 */
export interface Engagement {
  id: number;
  verrerie: number | Verrery;
  /**
   * Sélectionnez une personnalité ou un verrier.
   */
  personneConcernee:
    | {
        relationTo: 'personnalites';
        value: number | Personnalite;
      }
    | {
        relationTo: 'verriers';
        value: number | Verrier;
      };
  /**
   * Précise si l'engagement est un rôle de direction/propriété ou un métier d'artisan/ouvrier.
   */
  typeEngagement: 'role_personnalite' | 'metier_verrier';
  /**
   * Ex: "Directeur Technique", "Souffleur de verre à bouteilles", "Maître Verrier".
   */
  fonctionOuMetier: string;
  /**
   * Ex: "1880-1890", "vers 1905", "actif en 1870"
   */
  periodeActiviteTexte: string;
  dateDebutEngagement?: string | null;
  dateFinEngagement?: string | null;
  descriptionEngagement?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verriers".
 */
export interface Verrier {
  id: number;
  nom: string;
  prenom?: string | null;
  /**
   * Généré automatiquement à partir du prénom et du nom si laissé vide, ou peut être saisi manuellement.
   */
  nomComplet?: string | null;
  slug?: string | null;
  /**
   * Ex: "vers 1787", "le 12/03/1850", "avant 1800"
   */
  dateDeNaissance?: string | null;
  /**
   * Sélectionnez le lieu de naissance si connu.
   */
  lieuDeNaissance?: (number | null) | Lieux;
  /**
   * Ex: "vers 1820", "le 01/10/1899", "après 1870"
   */
  dateDeDeces?: string | null;
  /**
   * Sélectionnez le lieu de décès si connu.
   */
  lieuDeDeces?: (number | null) | Lieux;
  periodePrincipaleActivite?: string | null;
  specialisation?: string | null;
  notesBiographie?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types-de-production".
 */
export interface TypesDeProduction {
  id: number;
  nom: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  verreriesProductrices?: (number | Verrery)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'verreries';
        value: number | Verrery;
      } | null)
    | ({
        relationTo: 'personnalites';
        value: number | Personnalite;
      } | null)
    | ({
        relationTo: 'verriers';
        value: number | Verrier;
      } | null)
    | ({
        relationTo: 'types-de-production';
        value: number | TypesDeProduction;
      } | null)
    | ({
        relationTo: 'engagements';
        value: number | Engagement;
      } | null)
    | ({
        relationTo: 'lieux';
        value: number | Lieux;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verreries_select".
 */
export interface VerreriesSelect<T extends boolean = true> {
  nomPrincipal?: T;
  slug?: T;
  nomsAlternatifs?:
    | T
    | {
        typeDeNom?: T;
        nom?: T;
        id?: T;
      };
  fondateurs?: T;
  dateDeCreation?:
    | T
    | {
        datePreciseCreation?: T;
        descriptionDateCreation?: T;
      };
  dateDeFermeture?:
    | T
    | {
        datePreciseFermeture?: T;
        descriptionDateFermeture?: T;
      };
  statutActuel?: T;
  notesStatutVestiges?: T;
  lieuPrincipal?: T;
  engagements?: T;
  typesDeProduction?: T;
  imagesEtMedias?: T;
  sourcesBibliographiques?:
    | T
    | {
        typeSource?: T;
        titre?: T;
        auteur?: T;
        url?: T;
        detailsPublication?: T;
        citationOuExtrait?: T;
        notesSource?: T;
        id?: T;
      };
  histoire?: T;
  techniquesInnovations?: T;
  aspectsSociaux?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnalites_select".
 */
export interface PersonnalitesSelect<T extends boolean = true> {
  nom?: T;
  prenom?: T;
  nomComplet?: T;
  slug?: T;
  rolePrincipal?: T;
  dateDeNaissance?: T;
  lieuDeNaissance?: T;
  dateDeDeces?: T;
  lieuDeDeces?: T;
  biographie?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verriers_select".
 */
export interface VerriersSelect<T extends boolean = true> {
  nom?: T;
  prenom?: T;
  nomComplet?: T;
  slug?: T;
  dateDeNaissance?: T;
  lieuDeNaissance?: T;
  dateDeDeces?: T;
  lieuDeDeces?: T;
  periodePrincipaleActivite?: T;
  specialisation?: T;
  notesBiographie?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types-de-production_select".
 */
export interface TypesDeProductionSelect<T extends boolean = true> {
  nom?: T;
  description?: T;
  verreriesProductrices?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagements_select".
 */
export interface EngagementsSelect<T extends boolean = true> {
  verrerie?: T;
  personneConcernee?: T;
  typeEngagement?: T;
  fonctionOuMetier?: T;
  periodeActiviteTexte?: T;
  dateDebutEngagement?: T;
  dateFinEngagement?: T;
  descriptionEngagement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lieux_select".
 */
export interface LieuxSelect<T extends boolean = true> {
  nomDuLieu?: T;
  adresse?: T;
  villeOuCommune?: T;
  codePostal?: T;
  departement?: T;
  region?: T;
  pays?: T;
  coordonnees?: T;
  notesHistoriquesSurLeLieu?: T;
  nomCompletAffichage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}